### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by bryanconnor** [CodeForBaltimore/codeforbaltimore.github.io#14]
Slated to be based on Code for America's : https://www.codeforamerica.org/privacy
Issue influenced by use of Google Analytics.

**Comment by jjhale** [comment]
Created a branch and made  a first stab at it with:
https://github.com/CodeForBaltimore/codeforbaltimore.github.io/blob/issue-14-add-pri-policy/privacy.md
